### PR TITLE
Add a new theme.

### PR DESCRIPTION
**Pull request by J3xLe1988B3lx0x2E6**
Hi. 
I add a new design from game Doki Doki Literature Club if you want to included it to your repository.
image
Just I made the theme of Monika.
image
And I modificate your script and file *theme.txt*.  😄 😃 
Finally, I tested on VirtualBox just I changed names of Operating systems.

### CODE REVIEW

**Comment by 13atm01** [comment]
> Hi. I add a new design from game Doki Doki Literature Club if you want to included it to your repository. image Just I made the theme of Monika. image And I modificate your script and file _theme.txt_. smile smiley Finally, I tested on VirtualBox just I changed names of Operating systems.

Hi
I've heard of it, is DDLC a galge game? :thinking: , I mean a dating game

Before adding it to my repository, may I give you a little advice and ask for your help?
* First
Looks like the text color is too blended with the background, maybe you can change the color according to the character's hair color 
193163878-3e9ad37d-c3de-4dd5-a8d9-79bdf914cbf3

* Second
Set the background at 1080p (ignore if you've done it)

* Third
It seems lacking if you only make one version of the character, it's better to make another version of the character so that other people can choose, and if I'm not mistaken there are four characters, right?

* Fourth
Will you help me in gathering resources?
Like giving a character image or logo without a background like this :arrow_down:  (You just need to provide the render, and I edited the words)
VTuber version

* Fifth
Tell me the official link of the game for copyright, and sorry I have to know your full name for copyright like this :arrow_down: 
Screenshot_20221001_003030


BTW, sorry for my bad english :smiling_face_with_tear:

**Comment by J3xLe1988B3lx0x2E6** [comment]
Ok 😄  I'll take your advices that you gave me and change some files and add characters of Natsuki, Sayori, and Yuri. 👍🏼 . 
The link of official website is [DDLC plus](https://ddlc.plus/). I recommend you.  Finally, I add my full name to script.

**Comment by J3xLe1988B3lx0x2E6** [comment]
There is a picture of them. Source on [DebiantArt](https://www.deviantart.com/sayoriplushvlogs/art/Doki-Doki-Chibi-Club-862197988)

image

**Comment by J3xLe1988B3lx0x2E6** [comment]
> > Hi. I add a new design from game Doki Doki Literature Club if you want to included it to your repository. image Just I made the theme of Monika. image And I modificate your script and file _theme.txt_. smile smiley Finally, I tested on VirtualBox just I changed names of Operating systems.
> 
> Hi I've heard of it, is DDLC a galge game? 🤔 , I mean a dating game
> 
> Before adding it to my repository, may I give you a little advice and ask for your help?
> 
> * First
>   Looks like the text color is too blended with the background, maybe you can change the color according to the character's hair color
>   193163878-3e9ad37d-c3de-4dd5-a8d9-79bdf914cbf3
> * Second
>   Set the background at 1080p (ignore if you've done it)
> * Third
>   It seems lacking if you only make one version of the character, it's better to make another version of the character so that other people can choose, and if I'm not mistaken there are four characters, right?
> * Fourth
>   Will you help me in gathering resources?
>   Like giving a character image or logo without a background like this ⬇️  (You just need to provide the render, and I edited the words)
>   VTuber version
> * Fifth
>   Tell me the official link of the game for copyright, and sorry I have to know your full name for copyright like this ⬇️
>   Screenshot_20221001_003030
> 
> BTW, sorry for my bad english 🥲

The files are changed and I added 4 themes.
**Chibi Version**
image

**Monika Version**
image
**Natsuki Version**
image

**Sayori Version**
image

**Yuri Version**
image

**Comment by 13atm01** [comment]
> Ok smile I'll take your advices that you gave me and change some files and add characters of Natsuki, Sayori, and Yuri. 👍🏼 . The link of official website is [DDLC plus](https://ddlc.plus/). I recommend you. Finally, I add my full name to script.

Nice 👍🏼, btw what's the difference between DDLC and DDLC plus?, which logo should I display later for description in this repository, is it DDLC or DDLC plus?

**Comment by 13atm01** [comment]
Ok I will merge this pull request, but before I promote it, I will test it for real on my laptop

And if you deign, may I have the raw design please?

**Comment by J3xLe1988B3lx0x2E6** [comment]
> > Ok smile I'll take your advices that you gave me and change some files and add characters of Natsuki, Sayori, and Yuri. 👍🏼 . The link of official website is [DDLC plus](https://ddlc.plus/). I recommend you. Finally, I add my full name to script.
> 
> Nice 👍🏼, btw what's the difference between DDLC and DDLC plus?, which logo should I display later for description in this repository, is it DDLC or DDLC plus?

DDLC is old version that is free on [steam](https://store.steampowered.com/app/698780/Doki_Doki_Literature_Club/)  and DDLC Plus adds new features for example substories that is no have a relation on original story, and new themes. (Pay version).
[DDLC](https://en.wikipedia.org/wiki/Doki_Doki_Literature_Club!) is based on Renpy and Python and [DDLC Plus](https://doki-doki-literature-club.fandom.com/wiki/Doki_Doki_Literature_Club_Plus!) is based on C# and Unity. Therefore, just change some features.

**Comment by 13atm01** [comment]
* There seems to be a few mistakes, I'll fix the install.sh and uninstall.sh files

Screenshot_20221002_044005

**Comment by 13atm01** [comment]
### **There are a few other mistakes**

* First
Monika version, the character drawing is a bit small, you have to adjust the size like Yuri version
detail1

* Second
Natsuki version, the character image is a little blurry/less clear
detail2

* Third
Sayori version, the details on her hands are broken
detail3

* Fourth
I want you to slightly blur the rounded part of the background in all versions including the chibi version, so that the captions are clearer/text color doesn't blend too well with the background
detail4

**Comment by 13atm01** [comment]
### **I'll leave the design work to you, and I'll fix the install.sh and uninstall.sh files on all versions**

**Comment by J3xLe1988B3lx0x2E6** [comment]
> ### **I'll leave the design work to you, and I'll fix the install.sh and uninstall.sh files on all versions**

Ok, so sorry I'm not so good designing  😅. And I fixed with new changes.

**Pull request merged**
