### PR TITLE
New Theme Touhou Project VideoGame

### PR DESCRIPTION
**Pull request by JohnKun136NVCP**
Hi. 
I've made a new Grub Theme about Touhou Project Special Edition, I proved in my local computer and it works. Try it on your virtual Machine or local and it works. So I changed the README because I changed my Profile name and username on Github, so some links didn't worked well.  Finally, I changed Doki Doki Backgroun onto *Sayori Theme*, also, so sorry about many commits but I forgot to make branches for every theme I've not finished yet, however I deleted them too, and I could't find a picture short about Touhou videogame for the README but I hope these pictures help you.

image
image
image
image

Any comment, please let me know

### CODE REVIEW

**Comment by 13atm01** [comment]
Interesting, Can I see a screenshot of the finished theme that you have tested first?

**Comment by JohnKun136NVCP** [comment]
> Interesting, Can I see a screenshot of the finished theme that you have tested first?

Yep. Sorry but my camara is not good. I took some photos to my local machine.
image
image
image

**Comment by 13atm01** [comment]
There seems to be a mistake in writing "select your operating system", you forgot the letter "A" in the word "operating" :laughing:

**Comment by JohnKun136NVCP** [comment]
> There seems to be a mistake in writing "select your operating system", you forgot the letter "A" in the word "operating" 😆

Hahaha, Yeah, XD. Let me fix it. 😆

**Comment by JohnKun136NVCP** [comment]
> > There seems to be a mistake in writing "select your operating system", you forgot the letter "A" in the word "operating" 😆
> 
> Hahaha, Yeah, XD. Let me fix it. 😆

Fixed xD

**Comment by 13atm01** [comment]
I will test it first, for the copyright please send me the official site link, and for the pict maybe you can send me the logo of the game like the one in the screenshot above (don't forget to send the logo in HD and png format) you can use this site :arrow_down: 

https://replicate.com/xinntao/realesrgan

**Comment by JohnKun136NVCP** [comment]
> I will test it first, for the copyright please send me the official site link, and for the pict maybe you can send me the logo of the game like the one in the screenshot above (don't forget to send the logo in HD and png format) you can use this site ⬇️
> 
> https://replicate.com/xinntao/realesrgan

A variant of the game is : https://global.touhoulostword.com/
Fanart
image

Official Logo:
image

**Comment by 13atm01** [comment]
I've tested it, now just the copyright part

Does Touhou Project not have an official website? :confused:

**Comment by JohnKun136NVCP** [comment]
> I've tested it, now just the copyright part
> 
> Does Touhou Project not have an official website? 😕

unfortunately, not 😞

**Comment by 13atm01** [comment]
I've finished it, you can see it in README.md

Thank you for being part of this repository, I did not expect this repository to get more than 150 stars, and more than 10 Fork
it turns out that there are also many weebs like me who like programming, Linux OS, and it turns out that there are also many developers who are also weebs :smile:

**Comment by JohnKun136NVCP** [comment]
> I've finished it, you can see it in README.md
> 
> Thank you for being part of this repository, I did not expect this repository to get more than 150 stars, and more than 10 Fork it turns out that there are also many weebs like me who like programming, Linux OS, and it turns out that there are also many developers who are also weebs 😄

Yeah, I've just seen it. He, he, well I love programming and thank you since you approved my PR and sorry, because I type fast that I eat some letters xD. So I gladded to collaborate you. I hope to finish other themes. 😄

**Pull request merged**
