### PR TITLE
Fix Background styles of DDLC Theme.

### PR DESCRIPTION
**Pull request by J3xLe1988B3lx0x2E6**
I changed Backgrounds of all versions of DDLC Theme.

### CODE REVIEW

**Comment by 13atm01** [comment]
### **Nice, now it looks even better :+1:**

**Comment by 13atm01** [comment]
- **Ok, I just finished one version**

Screenshot_20221003_024007

**Comment by J3xLe1988B3lx0x2E6** [comment]
> ### **Nice, now it looks even better 👍**

👍🏼 Thank you

**Comment by 13atm01** [comment]
Ok everything is almost done
doki_doki_chibi_club

**Comment by J3xLe1988B3lx0x2E6** [comment]
> Ok everything is almost done doki_doki_chibi_club

Wow 😮 it's so cute.

**Comment by 13atm01** [comment]
Everything is done, even I have added it to pling/gnome-look website, you can tell your friends or promote it to your group

### **Thanks for everything, I'm very happy there is a new version, and now this repository is starting to get a lot of visitors**

https://github.com/13atm01/GRUB-Theme/blob/master/README.md

**Comment by 13atm01** [comment]
btw, you can give a rating on the website pling/gnome-look

**Comment by J3xLe1988B3lx0x2E6** [comment]
Well, I fixed some things and I added select bar with different style  to all of themes. If you want to make a new pull request to add them.

**Monika Theme.**
monika-try
**Natsuki Theme**
natsuki-try
**Sayori Theme**
sayori-try
**Doki Doki Chibi version**
doki-doki

**Comment by 13atm01** [comment]
Seems more suitable this one, which uses the select bar

you can make a pull request now, I will fix the preview in README.md after you make a pull request

**Pull request merged**
